server:
  port: 8089
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: xiuxiu
    password: Cykj1912
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://rm-wz9gr12fyy61l72c00o.mysql.rds.aliyuncs.com/smart_bus_platform?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      test-while-idle: true
      validation-query: select 1
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      test-on-borrow: false
      test-on-return: false
      keep-alive: true
  redis:
    host: 120.25.211.135
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 500
        min-idle: 0
    lettuce:
      shutdown-timeout: 0

    timeout: 5000ms
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  application:
    name: userapp
  servlet:   #配置文件上传的大小
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB
eureka:
  client:
    register-with-eureka: true #是否从eureka服务器获取各个为服务地址
    fetch-registry: true #是否注册到eureka服务器
    service-url:
      defaultZone: http://localhost:8761/eureka/
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.cykj.pojo
  config-location: classpath:mybatis.xml
feign:
  hystrix:
    enabled: false #开启feign熔断，默认为false
  client:
    config:
      default:
        connect-timeout: 240000
        read-timeout: 240000
ftpclient:
  host: 120.25.211.135
  port: 21
  username: ftpuser
  password: ftpuser
  basePath: /home/ftpuser/
  filePath: /
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 50000





