server:
  port: 8999
spring:
  application:
    name: service-zuul
eureka:
  client:
    register-with-eureka: true #是否从eureka服务器获取各个为服务地址
    fetch-registry: true #是否注册到eureka服务器
    service-url:
      defaultZone: http://localhost:8761/eureka/
#配置路由
zuul:
  routes:
    user: /user/**
    admin: /admin/**
    city_line: /city_line/**
    userapp: /userapp/**
    visit-static:
      path: /static/**
      url: http://localhost:8081/static/
  host:
    connect-timeout-millis: 120000
    socket-timeout-millis: 120000
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 50000

